logging:
  level:
    root: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    password: Guille1439.
    url: jdbc:mysql://localhost:3306/ventas
    username: guillealedo
